APP_LABEL = Dropbear
APP_BINARY_NAME = Dropbear-App
APP_DESCRIPTION = Dropbear SSH Server

APP_LABEL_SLUG = $(shell echo "$(APP_LABEL)" | tr ' ' '_')
BUILD_DIR = build/$(APP_LABEL_SLUG)
OUT = $(BUILD_DIR)/$(APP_BINARY_NAME)

# Dropbear configuration
DROPBEAR_DIR = dropbear
DROPBEAR_BINARIES = dropbear dbclient dropbearkey scp

# Source files
SRC = src/main.cpp \
      src/Application.cpp \
      src/DropbearManager.cpp \
      src/NetworkManager.cpp \
      src/PathHelper.cpp \
      src/Renderer.cpp

# Object files
OBJ = $(SRC:src/%.cpp=$(BUILD_DIR)/obj/%.o)

# Test configuration
TEST_DIR = tests
TEST_BUILD_DIR = build/tests
TEST_SRC = $(TEST_DIR)/test_main.cpp \
           $(TEST_DIR)/test_PathHelper.cpp \
           $(TEST_DIR)/test_NetworkManager.cpp \
           $(TEST_DIR)/test_Color.cpp
TEST_OBJ = $(TEST_SRC:$(TEST_DIR)/%.cpp=$(TEST_BUILD_DIR)/obj/%.o)
TEST_OUT = $(TEST_BUILD_DIR)/test_runner

# Shared object files (excluding main.cpp)
SHARED_SRC = src/PathHelper.cpp \
             src/NetworkManager.cpp
SHARED_OBJ = $(SHARED_SRC:src/%.cpp=$(TEST_BUILD_DIR)/obj/shared/%.o)

# Use toolchain from env (already set to aarch64-linux-gnu-g++)
CXX ?= aarch64-linux-gnu-g++
HOST_CXX ?= g++

# Pull includes/libs from the environment (see `env` output)
CXXFLAGS += $(SDL_CFLAGS) -I. -DUSE_SDL
LDFLAGS  += $(SDL_LDFLAGS)
LIBS     += $(SDL_LIBS)

# Test build uses host compiler (tests run on build machine)
TEST_CXXFLAGS = -I. -std=c++11 -DUSE_SDL $(shell sdl2-config --cflags)
TEST_LDFLAGS = $(shell sdl2-config --libs)
TEST_LIBS = -lpthread -lSDL2_ttf

all: $(OUT) copy_resources

dropbear-binaries:
	@echo "Building Dropbear binaries..."
	@if [ ! -d "$(DROPBEAR_DIR)" ]; then \
		echo "Error: Dropbear submodule not found. Run: git submodule update --init --recursive"; \
		exit 1; \
	fi
	@cd $(DROPBEAR_DIR) && \
	( \
		unset CC CXX CPP CFLAGS CXXFLAGS LDFLAGS LIBS; \
		export CC=gcc; \
		export CPP="$$CC -E"; \
		export ac_cv_c_undeclared_builtin_options='none needed'; \
		{ \
			echo '/* Auto-generated by Makefile */'; \
			echo ''; \
			echo '/* Enable server/client password authentication */'; \
			echo '#define DROPBEAR_SVR_PASSWORD_AUTH 1'; \
			echo '#define DROPBEAR_CLI_PASSWORD_AUTH 1'; \
			echo ''; \
			echo '/* Minimal hostkey/public key algorithms: RSA only */'; \
			echo '#define DROPBEAR_RSA      1'; \
			echo '#define DROPBEAR_DSS      0'; \
			echo '#define DROPBEAR_ECDSA    0'; \
			echo '#define DROPBEAR_ED25519  0'; \
			echo ''; \
			echo '/* Optional: shrink code size slightly */'; \
			echo '#define DROPBEAR_SMALL_CODE 1'; \
		} > localoptions.h; \
		make clean || true; \
		./configure \
			--disable-zlib \
			--disable-pam \
			--enable-static \
			--enable-bundled-libtom; \
		make \
			PROGRAMS="dropbear dbclient dropbearkey scp" \
			CRYPTLIB="-lcrypt" \
			LDFLAGS="-static"; \
	)
	@echo "Dropbear binaries built successfully"

check-dropbear:
	@missing=""; \
	for bin in $(DROPBEAR_BINARIES); do \
		if [ ! -f "$(DROPBEAR_DIR)/$$bin" ]; then \
			missing="$$missing $$bin"; \
		fi; \
	done; \
	if [ -n "$$missing" ]; then \
		echo "Missing Dropbear binaries:$$missing"; \
		echo "Building Dropbear..."; \
		$(MAKE) dropbear-binaries; \
	fi

test: $(TEST_OUT)
	@echo "Running tests..."
	@$(TEST_OUT)

$(BUILD_DIR):
	mkdir -p $@
	mkdir -p $(BUILD_DIR)/obj

$(TEST_BUILD_DIR):
	mkdir -p $@
	mkdir -p $(TEST_BUILD_DIR)/obj
	mkdir -p $(TEST_BUILD_DIR)/obj/shared

$(BUILD_DIR)/obj/%.o: src/%.cpp | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OUT): $(OBJ) | $(BUILD_DIR)
	@$(MAKE) check-dropbear
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS) $(LIBS)

# Test build rules
$(TEST_BUILD_DIR)/obj/%.o: $(TEST_DIR)/%.cpp | $(TEST_BUILD_DIR)
	$(HOST_CXX) $(TEST_CXXFLAGS) -c $< -o $@

$(TEST_BUILD_DIR)/obj/shared/%.o: src/%.cpp | $(TEST_BUILD_DIR)
	$(HOST_CXX) $(TEST_CXXFLAGS) -c $< -o $@

$(TEST_OUT): $(TEST_OBJ) $(SHARED_OBJ) | $(TEST_BUILD_DIR)
	$(HOST_CXX) $(TEST_CXXFLAGS) $^ -o $@ $(TEST_LDFLAGS) $(TEST_LIBS)

copy_resources: | $(BUILD_DIR)
	# Copy icon into folder
	cp res/icon.png $(BUILD_DIR)/icon.png

	# Create config.json
	echo '{' > $(BUILD_DIR)/config.json
	echo '  "label":"$(APP_LABEL)",' >> $(BUILD_DIR)/config.json
	echo '  "icon":"icon.png",' >> $(BUILD_DIR)/config.json
	echo '  "iconsel":"icon.png",' >> $(BUILD_DIR)/config.json
	echo '  "launch":"launch.sh",' >> $(BUILD_DIR)/config.json
	echo '  "description":"$(APP_DESCRIPTION)"' >> $(BUILD_DIR)/config.json
	echo '}' >> $(BUILD_DIR)/config.json

	# Create launch.sh
	echo '#!/bin/sh' > $(BUILD_DIR)/launch.sh
	echo 'cd $$(dirname "$$0")' >> $(BUILD_DIR)/launch.sh
	echo '' >> $(BUILD_DIR)/launch.sh
	echo 'export LD_LIBRARY_PATH=$$(dirname "$$0")/lib:$$LD_LIBRARY_PATH' >> $(BUILD_DIR)/launch.sh
	# Logfile handling
	echo 'LOGFILE="app.log"' >> $(BUILD_DIR)/launch.sh
	echo 'echo "Launching $(APP_BINARY_NAME) - logging to $$LOGFILE"' >> $(BUILD_DIR)/launch.sh
	echo './$(APP_BINARY_NAME) > "$$LOGFILE" 2>&1' >> $(BUILD_DIR)/launch.sh
	chmod +x $(BUILD_DIR)/launch.sh

	# Copy font into res folder
	mkdir -p $(BUILD_DIR)/res
	cp res/arial.ttf $(BUILD_DIR)/res/

	# Copy dropbear binaries from dropbear/ directory
	@for bin in $(DROPBEAR_BINARIES); do \
		if [ -f "$(DROPBEAR_DIR)/$$bin" ]; then \
			cp $(DROPBEAR_DIR)/$$bin $(BUILD_DIR)/; \
		fi; \
	done

clean:
	rm -rf build

clean-all: clean
	@echo "Cleaning Dropbear build artifacts..."
	@if [ -d "$(DROPBEAR_DIR)" ]; then \
		cd $(DROPBEAR_DIR) && make clean || true; \
		rm -f $(DROPBEAR_DIR)/localoptions.h; \
	fi

.PHONY: all clean clean-all copy_resources test dropbear-binaries check-dropbear
